#!/bin/bash -eux

source "$(dirname $0)/bin/conf"
gitpwd=$(openssl rsautl -decrypt -inkey /home/radipi/passxem/seckey -in /home/radipi/passxem/cipher)

[ "$USER" = "root" ]

mkdir -p "$logdir"
chown www-data:www-data "$logdir"

### INSTALL THIS SYSTEM ###
rsync -av --delete "$(dirname $0)/bin/" "$appdir/"
chown www-data:www-data "$appdir" -R

### RENAME FETCH CGI ###
cd "$appdir"
rnd=$(cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c 32)

[ -e "/home/radipi/rnd" ] && rnd=$(cat /home/radipi/rnd )
mv "fetch" "fetch_$rnd.cgi"

### PULL ARTICLE REPO ###
rm -rvf "${contentsdir:?}"
cd "$wwwdir"

git clone "https://$contents_owner:$gitpwd@github.com/$contents_owner/$contents"
chown www-data:www-data "$contentsdir" -R

echo "call fetch_$rnd.cgi from GitHub"
