#!/bin/bash -eux

source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ]

### CREATE DIRECTORIES ###
mkdir -p "$logdir" "$datadir" "$datadir/counters"
chown www-data:www-data "$logdir" "$datadir" "$datadir/counters"

### INSTALL THIS SYSTEM ###
rsync -av --delete "$(dirname $0)/bin/" "$appdir/"
chown www-data:www-data "$appdir" -R
echo "$appdir copied.";

[ $# -eq 1  ] &&  [ "$1" = "clean" ] || { echo "deploy stopped. (skip rename fetch, remove article repository) if you want to do it, set 'clean' to \$1."; exit ; }

### RENAME FETCH CGI ###
cd "$appdir"
rnd=$(cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c 32)

[ -e "/home/radipi/rnd" ] && rnd=$(cat /home/radipi/rnd )
mv "fetch" "fetch_$rnd.cgi"

### PULL ARTICLE REPO ###
rm -rvf "${contentsdir:?}"
cd "$optdir"

git clone "https://github.com/$contents_owner/$contents_repo.git" $contents
chown www-data:www-data "$contentsdir" -R

echo "call fetch_$rnd.cgi from GitHub"
